### ISSUE TITLE
Working example with LibGDX

### ISSUE THREAD

**Issue by 10urshin** [kotlin-graphics/imgui#100]
Can we get a working example with LibGDX and LWJGL3 backend. I tried old example but imgui.impl.LwjglGL3 doesn't seems to exists anymore.

**Comment by Sylvyrfysh** [comment]
Looking at the code, you should just need to replace `ImplGL3` with `ImplBestGL`, and instead of `ImplGL3.INSTANCE`, use `new ImplBestGL()`.

**Comment by 10urshin** [comment]
> Looking at the code, you should just need to replace `ImplGL3` with `ImplBestGL`, and instead of `ImplGL3.INSTANCE`, use `new ImplBestGL()`.

That and adding 

`
    implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-stb"
    runtimeOnly "org.lwjgl:lwjgl::natives-windows"
    runtimeOnly "org.lwjgl:lwjgl-stb::natives-windows"
`
to dependencies fixed it.

[HelloImgui.kt.txt](https://github.com/kotlin-graphics/imgui/files/3638723/HelloImgui.kt.txt)
[build.gradle.txt](https://github.com/kotlin-graphics/imgui/files/3638724/build.gradle.txt)
