### ISSUE TITLE
How to add uno.glfw.glfwwindow?

### ISSUE THREAD

**Issue by ejamshidiasl** [kotlin-graphics/imgui#101]
Hello
how to find jar file?

**Comment by Sylvyrfysh** [comment]
How are you getting imgui? Gradle, Jar, Maven?

**Comment by ejamshidiasl** [comment]
jar

**Comment by Sylvyrfysh** [comment]
You can grab the latest uno-sdk-all.jar at [https://github.com/kotlin-graphics/uno-sdk/releases](https://github.com/kotlin-graphics/uno-sdk/releases). If possible, I would recommend adding gradle or maven support to your project so you can specify the imgui dependencies and have uno and other required libraries grabbed for you.
