### ISSUE TITLE
Problem with window close

### ISSUE THREAD

**Issue by ebak** [kotlin-graphics/imgui#106]
Code snippet:

```
val res = begin("Window", ::closed)
print("res: $res, closed: $closed\n")
```
![image](https://user-images.githubusercontent.com/4029399/69492816-9926b700-0ea7-11ea-9b03-f392dd41be2f.png)

Even if I press the (X) on the upper right corner, `res` and `closed` doesn't change:
```
res: true, closed: false
res: true, closed: false
res: true, closed: false
res: true, closed: false
res: true, closed: false
res: true, closed: false
```

Is it possible to implement window close with pressing on (X)?

[dependencies.txt](https://github.com/kotlin-graphics/imgui/files/3883406/dependencies.txt)

**Comment by exuvo** [comment]
Yes it is. I use mine like this and close with x works:

`
var mainDebugVisible = false

// In draw function
```
if (mainDebugVisible) {
  if (ImGui.begin("Debug window", ::mainDebugVisible, WindowFlag.MenuBar.i)) {
    ImGui.text("Hello, world %d", 4)
  }
  ImGui.end()
}
```

Then elsewhere i also have a key bound to toggle the variable and window visibility.
```
fun keyAction(action: KeyActions_ImGuiScreen): Boolean {
  if (action == KeyActions_ImGuiScreen.DEBUG) {
    mainDebugVisible = !mainDebugVisible;
    return true;
  }
  return false
}
```

**Comment by elect86** [comment]
@exuvo has right, you shall check against the return value.

Also, in general to optimize you may want to quit early if the window is collapsed

like [here](https://github.com/kotlin-graphics/imgui/blob/master/imgui-core/src/main/kotlin/imgui/demo/ExampleApp.kt#L119-L122)

Also, it looks like `closed` may be only set to false, if clicked the [close button](https://github.com/kotlin-graphics/imgui/blob/master/imgui-core/src/main/kotlin/imgui/classes/Window.kt#L873)

**Comment by elect86** [comment]
@ebak I'll close it. If you think otherwise, feel free to reopen it
