### ISSUE TITLE
KotlinNullPointerException when closing popup

### ISSUE THREAD

**Issue by exuvo** [kotlin-graphics/imgui#107]
I'm getting a KotlinNullPointerException when closing a popup with closeCurrentPopup() that had no navWindow selected before opening the popup. I'm using com.github.kotlin-graphics.imgui:imgui-gl/glfw/core:-SNAPSHOT from today.

Stacktrace says it is thrown at imgui.imgui.imgui_popupsModals$DefaultImpls.closeCurrentPopup(popups.kt:175)
The line there (also last line of function) is:
g.navWindow?.dc!!.navHideHighlightOneFrame = true

When i catch the exception right after the call to closeCurrentPopup(), g.navWindow is null but there is already a null check "?" there so i don't understand why the exception is thrown. Obviously no exception if i had a window selected before opening the popup as g.navWindow is then not null when pre-popup stack is restored.

Minimal test case would be:
```
if (ImGui.begin("test2")) {
  ImGui.text("Hello, world")
  ImGui.end()
}

ImGui.openPopup("test");
if (ImGui.beginPopup("test")) {
  if(ImGui.button("close")) {
    try {
      ImGui.closeCurrentPopup();
    } catch (err: NullPointerException) {
      err.printStackTrace()
    }
  }
  ImGui.endPopup();
}
```

No errors clicking on close at first, but if you click once outside both the popup and the window and then try close you get the nullexception as the test2 window is no longer selected and navWindow is null.

Noticed this as i have ported the pie menu widget from https://github.com/ocornut/imgui/issues/434#issuecomment-351743369 over to kotlin, which works great except for for when i close a piemenu which was opened without a currently selected window. Current workaround is to trycatch ignore the exception around closeCurrentPopup.

**Comment by elect86** [comment]
Let's try with `g.navWindow?.dc?.navHideHighlightOneFrame = true`

I dont get anything, but I'll wait for your feedback

Also, that pie menu looks great, if you'd like to add it, don't hesitate

**Comment by exuvo** [comment]
Yep that seems to have fixed it.

I'll see about adding it when i have tested it some more. Code needs some cleanup.
