### ISSUE TITLE
inputText width problems

### ISSUE THREAD

**Issue by SpaiR** [kotlin-graphics/imgui#108]
After updating my dependecies accordinaly to this commit `bfb0cc4fcd86e74158b4937748c00e042a208a08` (with this one `e1fbe03a0a6ee59bd239f6f20d2f5d9275789f86` for imgui specifically) I found that `ImGui.inputText()` now behaves incorrectly. See screenshot below.

![image](https://user-images.githubusercontent.com/12721311/69887556-91786f80-12f8-11ea-87fa-180f63c68eb7.png)

Right now `inputText()` will produce small field like this one and you can't change its size (`setNextItemWidth` doesn't work).

I think that the bug could be found in `Vec2::anyNotEqual` method. Because right now it behaves incorrectly (`Vec2(-1, -1).anyNotEqual(0f)` will return `false`).

**Comment by elect86** [comment]
Hi,

it shall be fixed now

I'll wait for your feedback

**Comment by SpaiR** [comment]
Yeah, now everything is works fine. Thank you!
