### ISSUE TITLE
Imgui should not depend on platform specifc native libraries

### ISSUE THREAD

**Issue by TheMrMilchmann** [kotlin-graphics/imgui#11]
Currently, the generated POM lists platform specific binaries as dependency (the LWJGL linux natives to be more specific). Since in reality imgui does not depend on a single platform this is bad behavior and unnecessary noise in the dependency graph.
I suggest making those binaries test dependencies and instruct users to add the following snippet (or something similiar) to their buildscripts:
```groovy
import org.gradle.internal.os.OperatingSystem

apply plugin: 'java'
apply plugin: 'kotlin'

repositories {
    mavenCentral()
    maven { url "https://dl.bintray.com/kotlin/kotlin-dev" }
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    maven { url 'https://jitpack.io' }
}

dependencies {
    compile 'com.github.kotlin-graphics:imgui:-SNAPSHOT'
	
    switch ( OperatingSystem.current() ) {
        case OperatingSystem.WINDOWS:
            ext.lwjglNatives = "natives-windows"
            break
        case OperatingSystem.LINUX:
            ext.lwjglNatives = "natives-linux"
            break
        case OperatingSystem.MAC_OS:
            ext.lwjglNatives = "natives-macos"
            break
    }

    // Look up which modules and versions of LWJGL are required and add setup the approriate natives.
    configurations.compile.resolvedConfiguration.getResolvedArtifacts().forEach {
        if (it.moduleVersion.id.group == "org.lwjgl") {
            runtime "org.lwjgl:${it.moduleVersion.id.name}:${it.moduleVersion.id.version}:${lwjglNatives}"
        }
    }
}
```

**Comment by elect86** [comment]
Hi,

yeah, I wanted to address this as well since some time, but never really did it.

It makes sense (although why the lwjgl linux native in particular?)

I just pushed and made jogl and lwjgl natives as test dependencies. I still need lwjgl on compile for the stb bindings, maybe this will change in the future when the original imgui will switch to trueType, but for the moment, unless I (or somebody else) finish that part (I attempt to port stb at begin and then I had to put that aside because of time) I see no other alternative.

About the instruct, would you mind writing them? I'll send you an invite

**Comment by TheMrMilchmann** [comment]
I assume that it was configured to use linux natives because that is what the Jitpack servers are running on. (Hence `OperatingSystem.current()` evaluated to linux and the generated POM only contained those dependencies.)

I made some minor changes in 8628903e887a2ab33acb995e45087824a734a6ad as well as in the [wiki](https://github.com/kotlin-graphics/imgui/wiki/Install).

**Comment by elect86** [comment]
Yep, that makes sense.

Thanks for the changes, much better than I'd have done otherwise :)

**Comment by elect86** [comment]
Hey, 

I had to revert temporarily `testRuntime` native to `runtime` in `build.gradle`, because of problems working with [fat jar](https://github.com/kotlin-graphics/imgui/issues/16)

Could you please look into that and give me a feedback about?
