### ISSUE TITLE
Can't import uno.glfw.GlfwWindow

### ISSUE THREAD

**Issue by zeroeightysix** [kotlin-graphics/imgui#112]
Looks like I'm experiencing the same issue as #101, but am using gradle to pull imgui dependencies in.
IntelliJ, or gradle while building - can resolve references to most imgui classes (e.g. `import imgui.ImGui;` works fine). However, `uno.glfw.GlfwWindow` just doesn't seem to exist, even though IntelliJ lists it in the dependencies just fine, and can even view its (decompiled) source code.

The `build.gradle` I'm using to reproduce this problem looks like this:
 ```gradle
plugins {
    id 'java'
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    compile 'com.github.kotlin-graphics:imgui:-SNAPSHOT'
}
```
The problem also persists with the more complete `build.gradle` listed on the wiki or in the README.

In an editor references to `GlfwWindow` cannot be resolved, but `ImGui` can:
![image](https://user-images.githubusercontent.com/27009727/71123318-a9019480-21e2-11ea-82fe-99de6f5010d6.png)

Running gradle's `build` task, it insists `uno.glfw` does not exist:
![image](https://user-images.githubusercontent.com/27009727/71123369-c2a2dc00-21e2-11ea-9468-bafe04e2de1a.png)

In the 'External Libraries' listing, the class **is** listed (and can be viewed without error):
![image](https://user-images.githubusercontent.com/27009727/71123671-75733a00-21e3-11ea-8dce-c44020244c16.png)

These results are produced using java version:
```
openjdk 11.0.5 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10)
OpenJDK 64-Bit Server VM (build 11.0.5+10, mixed mode)
```

If I switch to OpenJDK 8, gradle will fail even before an error for `GlfwWindow`, producing the following error:
```
/home/ridan/IdeaProjects/imguitest/src/main/java/Main.java:1: error: cannot access ImGui
import imgui.ImGui;
            ^
  bad class file: /home/ridan/.gradle/caches/modules-2/files-2.1/com.github.kotlin-graphics.imgui/imgui-core/-SNAPSHOT/55853bf32a87b9129ac7c136ca312354dc2083e2/imgui-core--SNAPSHOT.jar(imgui/ImGui.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

However, If I use the `jdk8` branch(es) made by @AlexApps99, the issue persists like it did with JDK 11.

Edit: any references to the `uno` package don't work.

If you need any more information, just ask. Thanks!

**Comment by zeroeightysix** [comment]
Looks like adding `uno-sdk` and `glm` explicitly fixes the issue:
```gradle
    compile "com.github.kotlin-graphics:imgui:-SNAPSHOT"
    compile 'com.github.kotlin-graphics:uno-sdk:f528113bf45e43406953d6881915467d85a20881'
    compile 'com.github.kotlin-graphics.glm:glm:1b4ac18dd1a3c23440d3f33596688aac60bc0141'
```
but that's not a very elegant or maintainable solution.

**Comment by elect86** [comment]
I guess this has to do with the gradle `implementation` keyword..

I use that explicitely to avoid any leaking of imgui dependencies into the application using imgui

but based on what you make here notice, it looks like indeed uno shall be switched to `api`

I dont understand why you need also glm though..

Do you want to do a quick test with another branch and `api uno`?

**Comment by zeroeightysix** [comment]
Of course. Please tell me what to do.

**Comment by zeroeightysix** [comment]
> I dont understand why you need also glm though..

It's the same problem.
`imgui.button(String string, Vec2 vec)` accepts a  `Vec2` - which I have to explicitly add (entire glm library) in order to be able to use it.

The same goes for the kotlin stdlib.
`imgui.showDemoWindow` can accept either a `boolean[]` or a `KMutableProperty`.
Even if I use the constructor that accepts a `boolean[]`, gradle complains:

(showDemoWindow is of type `boolean[]`)
```
/home/ridan/IdeaProjects/kami/src/main/java/me/zeroeightsix/kami/gui/KamiGuiScreen.java:52: error: cannot access KMutableProperty0
            imgui.showDemoWindow(showDemoWindow);
                 ^
  class file for kotlin.reflect.KMutableProperty0 not found
```

adding stdlib fixes it again:
```gradle
    compile group: 'org.jetbrains.kotlin', name: 'kotlin-stdlib', version: '1.3.61'
```

**Comment by elect86** [comment]
- create a new branch
- change `implementation` to `api` in `uno-gl` ([here](https://github.com/kotlin-graphics/imgui/blob/master/imgui-gl/build.gradle#L19))
- commit and copy the corresponding revision number (in Idea git Log view, right click on the commit, "Copy ..")
- comment the explicit `compile` (which is deprecated btw, use `implementation`)
- request the very same commit in your program and 


request exactly the very same commit instead `-SNAPSHOT`


Also: you dont need all the backends, imports only what you really need, which is (I think) the gl backend

```
["core", "gl"].each {
        implementation "${kx}.uno-sdk:uno-$it:$uno_version"
    }
```

Ps: yep, true, glm is needed as well (and kotlin reflect, which is weird though)

**Comment by zeroeightysix** [comment]
I tried with this commit: https://github.com/kotlin-graphics/imgui/commit/8f910122ffb0a64e80a993dfb739235d5f176753
Unfortunately, the same problem persists.

**Comment by elect86** [comment]
- be sure you have the imgui with the right commit version requested
- try also the same in the `core` module

And import only those two

**Comment by zeroeightysix** [comment]
Using this:
```gradle
ext {
    imguiVersion = "2f61b9e67433573841857a5ab3f763e69ac594a7"
}
["gl", "core"].each {
    implementation("com.github.kotlin-graphics.imgui:imgui-$it:$imguiVersion")
}
```
(commit 2f61b9e67433573841857a5ab3f763e69ac594a7)

The problem persists. Am I doing something wrong?

**Comment by elect86** [comment]
Apparently no.

I might have a similar playground where I could test this, but it still require a lot of re-work before reaching a buildable status (it's the vulkan sample port of sascha), which means not in the short term future

You may want to open an issue on StackOverflow targetting explicitely gradle

**Comment by zeroeightysix** [comment]
Okay, will do. Thanks for the help (and the amazing libraries)!

**Comment by exuvo** [comment]
I just realised this is actually the same problem i had in #143 . If you would have opened intellij module settings -> dependencies in the right part you would have seen that uno-sdk is listed only as scope runtime but should be compile. Should be fixed with next release when dependencies for uno-core and glm are changed to api from implementation (as that resolves it in my local branch).

**Comment by elect86** [comment]
this should be solved
