### ISSUE TITLE
Issue with java 11, is it possible to build for java 8 ?

### ISSUE THREAD

**Issue by Wicpar** [kotlin-graphics/imgui#124]
Hi, 

I replaced vulkan with imgui due to frequent crashes, it works great.

The issue is i cannot build my game for macos anymore because the latest java version the gradle plugin supports is 8...

Is there a reason the library has to be built with the JDK 11 ? Is is possible to build it for java 8?

**Comment by elect86** [comment]
Hi Wicpar!

What do you mean by replacing vulkan with imgui?

Anyway, there is a guy mantaining a jdk8 version in the `jdk8` branch, you may want to try that

**Comment by Wicpar** [comment]
Oh great, i meant nuklear, the k confused my tired and irritated self.
