### ISSUE TITLE
Upload artifact after actions build

### ISSUE THREAD

**Issue by zeroeightysix** [kotlin-graphics/imgui#126]
Now that we're working with GitHub actions, maybe consider uploading the built jar with every successful build.

This can be done quite easily using [upload-artifact](https://github.com/actions/upload-artifact). Developers who still choose to manually include the prebuilt jar file will then be able to easily download the latest jar from the actions page.

**Comment by elect86** [comment]
Sure, wanna start trying it by yourself?

**Comment by zeroeightysix** [comment]
> Sure, wanna start trying it by yourself?

Okay, I'll make a PR soon.

**Comment by elect86** [comment]
Btw, write me an email, I'll reward you with some money for your last commits
