### ISSUE TITLE
[Suggestion] Provide another package compiled with target Java 8

### ISSUE THREAD

**Issue by hnOsmium0001** [kotlin-graphics/imgui#133]
Since one of the targets of this library this Minecraft, and Forge doesn't support anything above Java 8 (yet), it would be very helpful to provide another build with `compileKotlin.kotlinOptions.jvmTarget = "1.8"`.
This way modders don't have to use weird workarounds to load this library anymore.

According to #124, there is a jdk8 branch, but itseems really outdated. I'm not an expert in Kotlin, but I thought it always supported compiling to java 8?

**Comment by Sylvyrfysh** [comment]
Java bytecode levels and java versions are two different things. Kotlin compiles to 1.8 bytecode, but that means nothing if we use Java 11 features. I'm not sure if we do, but I may tinker around with it and see.

**Comment by elect86** [comment]
this is fixed by `-jdk8` branch
