### ISSUE TITLE
framebufferScale is not cloned

### ISSUE THREAD

**Issue by tobias-dv-lnu** [kotlin-graphics/imgui#134]
We're working on a OSX version of a project using imgui and as it seems the framebufferScale variable is not cloned in fun clone(): DrawData.

This results in a framebufferScale of 0,0 which gives very small windows :)

**Comment by elect86** [comment]
Hi tobias,

feel free to submit a PR, otherwise I'll take care of it the next iteration (working on the tests right now)

**Comment by tobias-dv-lnu** [comment]
done :) Though I will mention that there seem to be some stability issues on OSX. E.g. demo crashes immediately or after some frames with error code 134 about 1 time in 4. However this is another issue and I will post more when/if I get some more concrete points.

**Comment by elect86** [comment]
thank, a dedicated issue with more details will be useful!
