### ISSUE TITLE
hmm how to use beginChildEx properly.

### ISSUE THREAD

**Issue by Dj-jom2x** [kotlin-graphics/imgui#146]
```java
imgui.beginChildEx("Hewwo", 0, new Vec2(200,300), false, 0);
imgui.endChild();
```

well, I will use this as another new window beside my imgui.begin one. but the title doesn't really work.. everything works besides title I don't want a debug title on my window. also how to make that close button appear on `beginchild`. as a default on `begin` the close button is there.. also X button is not even listed in the flag. might be good if it's listed as a flag WindowFlag.NoClose something. 

so another window looks like this 

![image](https://user-images.githubusercontent.com/12135498/90954261-6b59b780-e4a5-11ea-9bdd-cde0ed392b34.png)

in the c++ version their beginechild ex looks like this
```c++
ImGui::BeginChild("scrolling");
ImGui::SetScrollX(ImGui::GetScrollX() + scroll_x_delta);
ImGui::EndChild();
```

I'm just using c++ docs and trying to make sense on the kotlin/java one hahaha help.

![image](https://user-images.githubusercontent.com/12135498/90954456-f12a3280-e4a6-11ea-9655-a8b5242681ce.png)

it does say name. is that not title of the child?

As alternative i tried popup but it only works on fresh open. next click it wont open any more..
```java
if (imgui.begin("AAAAAA AAAAAAAAAA AAAAAAAAA", null, 0, WindowFlag.AlwaysAutoResize.i + WindowFlag.NoResize.i)) {
			imgui.text("AAAAAAA AAAAAAA: AAAAAAAA");
			imgui.spacing();
			if (imgui.collapsingHeader("AAAAAA AAAAAAA", 0)) {
				imgui.spacing();
				imgui.text("AAAAAA AAAAAAAA: AAAAAAA");
				if (imgui.button("Open Me", new Vec2(60, 20))) {
					imgui.openPopup("hello");
				}

				if (imgui.beginPopupModal("hello", open, WindowFlag.AlwaysAutoResize.i)) {
					imgui.text("im a text lol");
					imgui.spacing();
					imgui.endPopup();
				} 
			}
		}
```

the idea of it I get in here.

https://github.com/ocornut/imgui/blob/7b0570d6bac96ed64d379d240907f8fee319d57b/imgui_demo.cpp#L2993-L3017
![image](https://user-images.githubusercontent.com/12135498/90954865-e4a7d900-e4aa-11ea-9582-33cb891f25c5.png)

**Comment by elect86** [comment]
May I ask why you closed this?

I was going to look at it in the next days..

**Comment by Dj-jom2x** [comment]
> May I ask why you closed this?
> 
> I was going to look at it in the next days..

because I thought this is how to make a new window. I find that making new begin and end begin is what I really looking for.  .. for making a new another window. using this beginChildEx is blocking all input on another window.. which is not what I'm looking for. its a mistake on my end.

but you know what, I still like to know how beginChildEx works. I can't change its title. It blocking input on parent window.. what is really used for. it's like a modal or something
