### ISSUE TITLE
popen at begin not updating. or am i doing something wrong?

### ISSUE THREAD

**Issue by Dj-jom2x** [kotlin-graphics/imgui#147]
in java

```java
boolean[] popen_yikes = new boolean[] { true }; 
UI.begin("Sample", popen_yikes, 0, WindowFlag.AlwaysAutoResize.i)
```
if I hit the X button should popen_yikes became false? I don't understand how to handle the close xD because it's not updating the popen_yikes

I mean on the checkbox

```java
boolean[] test = new boolean[] { false }; 
UI.checkbox(" say hi?", test);
```

why the test gets updated? 

and not the popen_yikes one.

**Comment by zeroeightysix** [comment]
Hmm, what does `UI#begin` look like? This is just a guess, but are you not calling `ImGui.end()` to finish drawing the window?

**Comment by Dj-jom2x** [comment]
its a 
```java
boolean[] isopen = {
    false
};

@Override
public void render(...........) {

    gui.ImGuiIO = UI.getIo();
    gui.implGl3.newFrame();
    gui.implGlfw.newFrame();
    UI.newFrame();

    if (UI.begin("sample1", isopen, WindowFlag.AlwaysAutoResize.i + WindowFlag.MenuBar.i)) {

        UI.end();
    }

    //test if its updating really since the above wont close
    System.err.println(isopen[0]);
    UI.render();
    gui.implGl3.renderDrawData(Objects.requireNonNull(UI.getDrawData()));
}
```
in checkbox it works tho ... since  imgui kotlin did that to counter KMutableProperty0 thingy
I feel the logic is the same but it's just not updating unlike checkboxes..

**Comment by Dj-jom2x** [comment]
yeah its totaly broken i just used the MutableProperty0 as
```
MutableProperty0<Boolean> hi = new MutableProperty0<>();
```
this one updates it..

```boolean imgui.ImGui.begin(@NotNull String name, @NotNull boolean[] pOpen, int flags)```
vs
```boolean imgui.ImGui.begin(@NotNull String name, @Nullable KMutableProperty0<Boolean> pOpen, int flags_)```

in java, the one with @NotNull boolean[] pOpen is broken only on the `begin` one.. because on checkboxes it works

**Comment by elect86** [comment]
@Dj-jom2x If you want, I can add you, so you can easily create a new branch and test there an hotfix for that

**Comment by exuvo** [comment]
ImGUI only changes the passed array value to `false` when close is clicked, it does nothing else at all with the value. So to stop it from drawing the window you need to use the variable in a if check for begin. Ex:
```
boolean[] isOpen = {true}; 

public void draw() {
	if (isOpen[0] && ImGui.INSTANCE.begin("test", isOpen, 0)) { // if close is clicked frame isOpen[0] becomes false
		ImGui.INSTANCE.text("test " + isOpen[0]); // will be seen as false 1 frame
		ImGui.INSTANCE.end();
	}
}
```

Just tested this and it works as expected. Also remember that if the boolean[] is a local variable it is only false 1 frame so keep it permanent.

**Comment by Dj-jom2x** [comment]
ooow only 1 frame. thanks for explaining :) I already change all my booleans to MutableProperty0 xD before I read this.. because MutableProperty0 is more readable. I guess i can close this now :)
