### ISSUE TITLE
demos or examples?

### ISSUE THREAD

**Issue by atorralb** [kotlin-graphics/imgui#15]
Can you please provide some demos or samples so I can use imgui with kotlin? 

Thank you!

**Comment by elect86** [comment]
Hi,

sure, just clone the  project and run this [test](https://github.com/kotlin-graphics/imgui/blob/master/src/test/kotlin/imgui/test_lwjgl.kt)

**Comment by atorralb** [comment]
# Hi,
# It looks awesome!

![2017-12-20 09_59_52-imgui lwjgl opengl3 example](https://user-images.githubusercontent.com/5326525/34216024-b280a712-e56c-11e7-95b9-10333826d29a.png)

I'm gonna be using imgui for a big project, so you'll be seeing me around here for a long time.

# Thank you so much!

**Comment by elect86** [comment]
Me gusta muchissimo que te gusta :D

You must be around for such a looong time because I need all the cool screenshots you can deliver, dear, no escape ^^

Ps: you can turn off debug messages with `DEBUG = false`

Don't hesitate opening it again if you need something else

**Comment by atorralb** [comment]
@elect86  
eres un amor!
I'll be posting my progress
but wait... do you speak spanish?
