### ISSUE TITLE
Sample project

### ISSUE THREAD

**Issue by FauxKiwi** [kotlin-graphics/imgui#162]
I have found this library on last Sunday and I wanted to use it in my project. I tried it by using the instructions on the wiki, but it didn't work. There were too much errors than I can enumerate. Then I cloned it and the example seemed to work (except of some bugs, but they are in a separate issue). I tried building artifacts and using modules, but I didn't find a solution.
***
So I wanted to ask: Is there any sample project using glfw, that I can inspect to find out, what I've done wrong and how it can be fixed? It would really help me (and perhaps even other people) out a lot, since I tried it for an eternity now.

**Comment by FauxKiwi** [comment]
I just figured it out, after I wrote this issue. I will close this now, but nevertheless a sample project would surely be nice.

**Comment by elect86** [comment]
Define simple project, something more than the sample?

**Comment by FauxKiwi** [comment]
Now my new project (I made it work now) is public (Pumpkin-Engine).
As a sample project I would like to see a project that is not contained in the imgui module but more independent.
And the wiki should be updated.
