### ISSUE TITLE
When I open a menu and click the mouse button on the other space (not on opening windows), program crash!

### ISSUE THREAD

**Issue by MetaPhyicers** [kotlin-graphics/imgui#164]
I open a menu like this，and I tried to close it by clicking the other no window place, then program crash
![bug](https://user-images.githubusercontent.com/42922793/101877322-c89a8580-3bc8-11eb-867f-f72f29f82872.png)

I run the Java example in IntelliJ IDEA, here is the report:
![report](https://user-images.githubusercontent.com/42922793/101876248-1910e380-3bc7-11eb-863c-ad39a3891c52.png)

**Comment by elect86** [comment]
Hi @MetaPhyicers,

Thanks for reporting, it should be fixed

Give it a try and then close if confirmed

ciao
