### ISSUE TITLE
./gradlew eclipse does not see the link

### ISSUE THREAD

**Issue by SprayDown** [kotlin-graphics/imgui#165]
![eclipse imgui error](https://user-images.githubusercontent.com/67624548/104689778-566c1200-572d-11eb-8eb3-6edc247169d4.PNG)

build :

dependencies {
	def dependency = { id ->
		modImplementation id
		shadow id
	}

	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	
	// ImGUI
		ext{
		imguiVersion = "-SNAPSHOT"
	}
	["gl", "glfw", "core"].each {
		implementation("com.github.kotlin-graphics.imgui:imgui-$it:$imguiVersion") {
			exclude group: "org.lwjgl"
		}
	}

	compile group: 'org.jetbrains.kotlin', name: 'kotlin-stdlib', version: '1.3.70'

	dependency "com.github.ZeroMemes:Alpine:1.9"
	dependency 'com.g00fy2:versioncompare:1.3.7'
	dependency "org.joml:joml:1.10.0"

**Comment by elect86** [comment]
Hey, sorry for the late reply

can you provide a public repo to try it out?
