### ISSUE TITLE
Shaders do not compile on M1 (macOS 11.4)

### ISSUE THREAD

**Issue by tasgon** [kotlin-graphics/imgui#171]
Trying to render anything results in a `glShader compile status false: ERROR: 0:2: '' :  version '150' is not supported` error. I've tried changing the `imgui.impl.gl.glslVersion` variable to 320 and 410 to no avail.

I am using custom-built native libraries of LWJGL 3.2.1 for aarch64 support. Could that be the source of the issue?

**Comment by Sylvyrfysh** [comment]
Hello there!

Does this issue happen under native code, or Rosetta execution?

**Comment by tasgon** [comment]
This happejs with native code.

**Comment by tasgon** [comment]
Turns out this was user error. I was attempting to use `ImplGL3` when I should have been using `ImplBestGL` for macOS support. My bad.
