### ISSUE TITLE
Use of `static` in package identifier can cause Java interoperability problems

### ISSUE THREAD

**Issue by tasgon** [kotlin-graphics/imgui#175]
One of the packages in `core` is `imgui.static`, however `static` is a reserved keyword and trying to refer to it from Java results in a [compile-time error](https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-IdentifierChars). Would it be possible to change the naming here?

If you'd rather, I can try to submit a PR for this change later today.

**Comment by elect86** [comment]
Thanks!
