### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by ForBai** [kotlin-graphics/imgui#189]
So i was trying to get this working in Minecraft (1.12.2) and looked in the wiki/readme and i noticed while implementing it that the wiki is outdated. I am not 100% sure about this issue but after reading some other issues i am very sure its just that the wiki is outdated.

**Comment by elect86** [comment]
Hello Forbai,

yes, that's, unfortunately, outdated

If you would like to help update it, don't hesitate
