### ISSUE TITLE
Rendering artifacts on non-square elements

### ISSUE THREAD

**Issue by doceazedo** [kotlin-graphics/imgui#191]
Everything that is not a square, such as most of the stuff on the demo custom rendering window, roundings and tabs are rendering with very weird, distorted artifacts:

<img width="1169" alt="CleanShot 2023-09-06 at 12 57 02@2x" src="https://github.com/kotlin-graphics/imgui/assets/33992396/dce0c79d-a11e-43b7-9597-026a16e130e8">

Some other artifacts are also appearing depending on the options:

https://github.com/kotlin-graphics/imgui/assets/33992396/60171f8c-3c5b-4afe-8fe6-dbd9951d8cd8

I didn't do anything fancy for the setup (note this is a Minecraft mod running on a Apple M1 Max, macOS 13.0.1):

```kt
object ImGui {
    val instance = ImGui
    val implGl3: ImplGL3
    val implGlfw: ImplGlfw

    init {
        MINECRAFT_BEHAVIORS = true

        val glfwWindow = GlfwWindow(MinecraftClient.getInstance().window.handle)
        val window = GlWindow(glfwWindow, Caps.Profile.COMPATIBILITY, true)

        window.makeCurrent(true)
        Context().setCurrent()

        implGlfw = ImplGlfw(window, false, null)
        implGl3 = ImplGL3()
    }
}
```

```kt
@Environment(EnvType.CLIENT)
open class ImGuiScreen(title: Text) : Screen(title) {
    override fun render(context: DrawContext?, mouseX: Int, mouseY: Int, delta: Float) {
        ImGui.implGl3.newFrame()
        ImGui.implGlfw.newFrame()
        ImGui.instance.newFrame()
        
        ImGui.instance.showDemoWindow(booleanArrayOf(true))
        
        ImGui.instance.render()
        ImGui.implGl3.renderDrawData(
            Objects.requireNonNull<DrawData>(ImGui.instance.drawData)
        )
    }
}
```

Any hints on how I can solve this?

**Comment by elect86** [comment]
Thanks for reporting

I got on the private test suite almost 300 tests, but that wasn't included.

It should be fixed now, fetch 1.89.7-1 and reopen this issue if it's still there
