### ISSUE TITLE
Multiple font size

### ISSUE THREAD

**Issue by Catvert** [kotlin-graphics/imgui#25]
Hi ! 
How can i handle multiple font size ? I tried to load 2 fonts from the same TTF and with a different pixels size but it crash immediatly without any stacktrace but with exit code -1073740940 (0xC0000374).

I used this code to load fonts 

```kotlin
var fontBytes = Constants.imguiFontPath.readBytes()
imguiDefaultFont = imgui.IO.fonts.addFontFromMemoryTTF(CharArray(fontBytes.size, { fontBytes[it].c }), 19f, FontConfig(), glyphRanges = imgui.IO.fonts.glyphRangesDefault)
imguiBigFont = imgui.IO.fonts.addFontFromMemoryTTF(CharArray(fontBytes.size, { fontBytes[it].c }),  30f, FontConfig(), glyphRanges = imgui.IO.fonts.glyphRangesDefault)
```

Is there any solution to have multiple font size with just one font ? 
Thanks, Catvert.

**Comment by Sylvyrfysh** [comment]
Do you get a hs_err_pidxxxx file?

**Comment by Catvert** [comment]
Oh yes : https://gist.github.com/Catvert/73054b2f6de3f1d6552d4ebfef6e6865 :)

**Comment by Sylvyrfysh** [comment]
This happens simply loading two fonts, same or different, for me. I'll look into fixes

**Comment by elect86** [comment]
It should be fixed now, there was an error in calculating some offsets

**Comment by Catvert** [comment]
It's working ! Thanks :)
