### ISSUE TITLE
lwjgl-stb native libs for windows and macos are missing

### ISSUE THREAD

**Issue by jpauty** [kotlin-graphics/imgui#27]
Hi,

I'm testing imgui with osx and windows. The native libs of lwjgl-stb for win and osx are not installed when using gradle. Only the linux libs are installed. These libs do exists. There must  be some missing dep somewhere in the gradle repository. 

I used this repository : https://jitpack.io/#kotlin-graphics/imgui

Cheers,

Julien

**Comment by elect86** [comment]
Hi Julien,

I've used it extensively under windows.

How do you include it?

**Comment by jpauty** [comment]
I've added the following repositories:
maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
jcenter()

Here are the compile dependencies (there are more but unrelated to the graphics), gdx version is 1.9.8:

compile "com.badlogicgames.gdx:gdx:$gdxVersion"
compile "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
compile "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
compile "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-desktop"
compile "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
compile "com.github.kotlin-graphics:imgui:-SNAPSHOT"

**Comment by elect86** [comment]
Try moving `maven { url 'https://jitpack.io' }` at last position under the repo section and grab imgui by the last commit:

`compile "com.github.kotlin-graphics:imgui:c6e179e0d3`

**Comment by jpauty** [comment]
Thank you for your help. Unfortunately, this does not solve the problem. Gradle only downloads the linux native libs. 

I'm using gradle 3.3, if that's of any use.

**Comment by elect86** [comment]
can you update it?

That's the only difference I can see at the moment

Try 4.5, you can simply modify your [`distributionUrl`](https://github.com/kotlin-graphics/imgui/blob/master/gradle/wrapper/gradle-wrapper.properties#L6)

**Comment by jpauty** [comment]
So it works. This was strange, I still don't have the macos and win native jars but it works. I don't have the dynamic loading error anymore.  So I looked into lwjgl-stb.jar and it contains the 3 native libs in addition to the java classes. What is strange is that I had the dynamic loading error in the first place. 

So maybe the  lwjgl-stb-natives-linux is redundant, but it does not seem to harm.

Anyway, closing.

**Comment by elect86** [comment]
Weird, but glad that it works
