### ISSUE TITLE
Are 1.5 shaders possible ?

### ISSUE THREAD

**Issue by jpauty** [kotlin-graphics/imgui#28]
Hi,

So my old mac book does not support the current shaders. I get the following error : 

Compiler failure in shader.vert shader: ERROR: 0:1: '' :  version '330' is not supported
ERROR: 0:9: 'layout' : syntax error: syntax error

This is strange because Apple claims it support OpenGl 3.3. The reported version is "3.3.0 Cocoa NSGL dynamic". 

I don't know anything about shaders, but they look sufficiently simple for me to think that it might be possible to convert them to 1.5. 

What do you think ? 

Regards,

Julien

**Comment by elect86** [comment]
Hi,

weird that too..

it should be quite easy to adapt them to 1.5 (I guess we just have to adjust the vertex layout)

give it a quick try, clone and try run with `#version 150`, remove also all the `(location = *)`

**Comment by jpauty** [comment]
Here is the state of the affairs,

I managed to convert the shaders to version 150 yesterday evening. This was a nice learning experience. I had to hack a bit gln because you must call glBindAttribLocation after the program creation and before glLinkProgram. This was the hard part for me: finding that I have to call glBindAttribLocation  to replace the layout calls.

I tried this on my macbook and still no luck. I get  version '150' is not supported. I believe this is not a version problem, because the sample code that comes with imgui works without any modification. I think there is some problem in the interaction between libgdx and imgui, somewhere something wrong happens. 

Maybe the call `LwjglGL3.init(GlfwWindow((Gdx.graphics as Lwjgl3Graphics).window.windowHandle), false)` is not sufficient.

**Comment by elect86** [comment]
> I managed to convert the shaders to version 150 yesterday evening. This was a nice learning experience. I had to hack a bit gln because you must call glBindAttribLocation after the program creation and before glLinkProgram. This was the hard part for me: finding that I have to call glBindAttribLocation to replace the layout calls. This works on my PC.

Yep, that was what I was referring to. We either call `glBindAttribLocation` and use the default vertex attributes location or `glGetAttribLocation`. Glad you enjoyed :)

If you would have warned me earlier maybe I could have make you avoid the hard part.. 

Anyway, to sum up, the demo works, but whenever you try to use it in libdx it doesnt.. right?

**Comment by jpauty** [comment]
> Anyway, to sum up, the demo works, but whenever you try to use it in libdx it doesnt.. right?
Exactly

**Comment by elect86** [comment]
I guess we should dig up then the initialization code in libgdx

And/or open an issue over there. Hopefully some dev will have some hints where this can come from

**Comment by elect86** [comment]
Hey, 

any news from your side?

From mine, I'm syncing at the moment imgui with the original and the current [delta](https://github.com/ocornut/imgui/compare/cea7492babfbd561589a41858159b14f0ca2373e...7fd62baa426b3f4a2d98c1510161bf1135dde7bc) introduce the possibility to lower the glsl version inside the shaders..

Theoretically I'd not be incline to give up some gl3.3 features (attribute locations) and add some additional code to make it compatible with older version (binding the locations before the program linking), but if this can help you, I'm more than happy to do it

**Comment by jpauty** [comment]
Hi,

I gave up on this issue. I'm sticking with libgdx gui for now :(

I don't think it's related to the glsl version because the sample that come with imgui works. It's the integration with libgdx which is somewhere broken (at least on my video card).

Time being limited, I won't try to fix this and stick with libgdx only. I believe this is far beyond my knowledge anyway.

You can close this issue, and just reopen it, if someone else faces the same issue.

Cheers

**Comment by elect86** [comment]
Ah pity..

Let me try to seduce you anyway :D

In the end changes were easier than I thought. Now for lwjgl, shaders require only 150.

If you ever want to give it a shot again, let me know and we'll open this issue and try again
