### ISSUE TITLE
Is LWJGL a required dependency?

### ISSUE THREAD

**Issue by empirephoenix** [kotlin-graphics/imgui#29]
Hi,
im currently in the progress of writing a binding for JME3. I noticed, that upon creating the Font
`		fontTexture = IO.INSTANCE.getFonts().getTexDataAsRGBA32();`
I get an expection:
```
java.lang.NoClassDefFoundError: org/lwjgl/system/MemoryUtil
	at uno.buffer.BufferKt.bufferBig(buffer.kt:18)
	at imgui.FontAtlas.addFontFromMemoryTTF(font.kt:160)
	at imgui.FontAtlas.addFontFromMemoryCompressedTTF(font.kt:176)
	at imgui.FontAtlas.addFontFromMemoryCompressedBase85TTF(font.kt:185)
	at imgui.FontAtlas.addFontDefault(font.kt:147)
	at imgui.FontAtlas.addFontDefault(font.kt:138)
	at imgui.FontAtlas.getTexDataAsAlpha8(font.kt:242)
	at imgui.FontAtlas.getTexDataAsRGBA32(font.kt:253)
	at ImGuiState.initialize(ImGuiState.java:25)
	at com.jme3.app.state.BaseAppState.initialize(BaseAppState.java:124)
	at com.jme3.app.state.AppStateManager.initializePending(AppStateManager.java:251)
	at com.jme3.app.state.AppStateManager.update(AppStateManager.java:281)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:236)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
	at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:197)
	at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:232)
	at java.lang.Thread.run(Thread.java:812)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.system.MemoryUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:444)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:490)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:376)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	... 17 more
```

So the question is, is lwjgl required for this? 
Or is there some way I can configure the system to use a different buffer implementation? 
Reason is, that I try to only use the official JME3 api for the binding in the hope that it will also work with jogl ect.
Greetings, Empire

**Comment by Sylvyrfysh** [comment]
Yes. You should not run into issues adding LWJGL core and STB however, which are the necessary pieces, as you won't ever touch openGL in LWJGL. However, I see one issue with this which I'll PR later. Until then, try adding LWJGL and seeing what happens.

**Comment by Sylvyrfysh** [comment]
Adding only the required LWJGL dependencies at this time should work, there are not issues where I though there would be.

**Comment by empirephoenix** [comment]
Yes, I get a bit further now, but there is still some issue with that buffer stuff.

```
Uncaught exception thrown in Thread[jME3 Main,5,main]
VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/lwjgl/system/MemoryUtil.memRealloc(Lorg/lwjgl/PointerBuffer;I)Lorg/lwjgl/PointerBuffer; @1: invokestatic
  Reason:
    Type 'org/lwjgl/PointerBuffer' (current frame, stack[0]) is not assignable to 'org/lwjgl/system/CustomBuffer'
  Current Frame:
    bci: @1
    flags: { }
    locals: { 'org/lwjgl/PointerBuffer', integer }
    stack: { 'org/lwjgl/PointerBuffer' }
  Bytecode:
    0x0000000: 2ab8 001a 1bb2 0015 b800 0fb8 0028 1bb8
    0x0000010: 0016 4d2a c600 142c c600 102c 2ab6 0030
    0x0000020: 1bb8 0026 b600 3157 2cb0               
  Stackmap Table:
    append_frame(@40,Object[#325])
```
Have you already seen this somewhere? running on jdk 1.8.0_131

**Comment by Sylvyrfysh** [comment]
do you get an actual stacktrace, or a hs_err_pid_* file?

**Comment by empirephoenix** [comment]
Only the one in the bottom. This looks like an jvm error actually, as Pointerbuffer directly extends Custombuffer, it should always be assignable. I will investigate further.

**Comment by empirephoenix** [comment]
apparently the lwjgl version I used is build with a buggy compiler, and should never have compiled in the first place O.o. I will try with another version later.

**Comment by elect86** [comment]
Hi Empire,

ideally we would have jogl as dependency only for the jogl implementation and similar for lwjgl.

However, we do also use lwjgl for the buffer management (creation, access e deletion) and the stb binding (although there were some attempts from the community to use [FreeType](https://github.com/ocornut/imgui/issues/618))

I'll forward your issue to spasi regarding lwjgl, to see if we can solve together :)

**Comment by empirephoenix** [comment]
I would offer to build a pull request, similar to the one I did back a while in JME3 
http://javadoc.jmonkeyengine.org/com/jme3/util/BufferAllocator.html
Basically it is a simple interface that tunnels all allocations, and can be set to a different implementation before startup. This allows jme to use specific allocators for lwjgl, jogl, directbytebuffers (with destroy reflection hack).

-> This would allow pure jvm logic by using directbytebuffers (eg for pure serverside to image rendering)
-> Using lwjgl or jogl based on the choosen driver. 

If you agree, I will try to prepare a pull request for this once done.

**Comment by Spasi** [comment]
@empirephoenix Based on the stacktraces above, it looks to me like you're trying to use JME3's lwjgl2 backend. imgui depends on lwjgl3, which is not at all compatible with lwjgl2 (e.g. `CustomBuffer` did not exist in lwjgl2). Obviously there's nothing wrong with how lwjgl3 has been compiled, etc.

Switching to the lwjgl3 backend should fix the weird issues.

**Comment by elect86** [comment]
Theoretically I have no problems with that..

But I guess we should operate at the [uno-sdk](https://github.com/kotlin-graphics/uno-sdk) level because I do all the buffer management there using lwjgl `MemoryUtil` class..

Anyway, uno-sdk depends on its turn on gli, which also uses lwjgl

So, if we/you want to change that we have to find a nice and good solution

**Comment by empirephoenix** [comment]
Actually trying to use it with the lwjgl 3 backend created it's own set of similar issues.

Where I currently have a few issues understanding the reason behind, as far as I understood the c++ imgui one of the big features is, that it is completely renderer agnostic and has no dependencies to opengl or directx (Or is this a misunderstanding?), so why does the port require an opengl implementation?

**Comment by Spasi** [comment]
It doesn't require OpenGL. It only uses the lwjgl-core (for memory management) and lwjgl-stb (for font rendering) modules.

**Comment by empirephoenix** [comment]
hm ok, lwjgl-stb has lwjgl full in the dependencies anyway, so there is not much won then.

**Comment by Spasi** [comment]
> Actually trying to use it with the lwjgl 3 backend created it's own set of similar issues.

Could you please post more details about this? Is there something about lwjgl3 that caused the issues?
