### ISSUE TITLE
renderer bug

### ISSUE THREAD

**Issue by Catvert** [kotlin-graphics/imgui#31]
Hi !
Since last commits (up feb 11-13-18), imgui doesn't render at all (with lwjgl3 at least) ! UI components are present but not displayed.

**Comment by elect86** [comment]
Salut Catvert,

imgui structure has slightly changed recently, `Context` isn't static anymore and `renderDrawData()` has been exposed

I just wrote a [post ](https://github.com/kotlin-graphics/imgui/issues/30#issuecomment-366690810)for empirephoenix highlighting all the important steps, you can take a look, it's basically the same for lwjgl

Let me know :)

**Comment by Catvert** [comment]
Thanks it's working !

**Comment by elect86** [comment]
Glad to know!

Ps: may you update the wiki accordingly?

**Comment by Catvert** [comment]
Of course ! I'm gonna do it at night. :)
