### ISSUE TITLE
NoSuchMethodError STBRPRect

### ISSUE THREAD

**Issue by Catvert** [kotlin-graphics/imgui#33]
Hi !
Since I refresh my gradle project, I have a NoSuchMethodError.
This is the stacktrace : 
`
Caused by: java.lang.NoSuchMethodError: org.lwjgl.stb.STBRPRect.was_packed()I
	at imgui.stb.ExtensionsKt.getWasPacked(extensions.kt:14)
	at imgui.FontAtlas.buildPackCustomRects(font.kt:821)
	at imgui.FontAtlas.buildWithStbTrueType(font.kt:633)
	at imgui.FontAtlas.build(font.kt:243)
	at imgui.FontAtlas.getTexDataAsAlpha8(font.kt:252)
	at imgui.FontAtlas.getTexDataAsRGBA32(font.kt:262)
	at imgui.impl.LwjglGL3.createFontsTexture(LwjglGL3.kt:245)
	at imgui.impl.LwjglGL3.createDeviceObjects(LwjglGL3.kt:176)
	at imgui.impl.LwjglGL3.newFrame(LwjglGL3.kt:108)
`
Thanks, Catvert.

**Comment by elect86** [comment]
Hi dear

what's your lwjgl version?

**Comment by Catvert** [comment]
Hi ! I've tried with the 3.1.4-3.1.5-3.1.6 but they all throw that exception :(

**Comment by elect86** [comment]
It looks like something is wrong with lwjgl..

if you `alt`-click `was_packed()` [here](https://github.com/kotlin-graphics/imgui/blob/master/src/main/kotlin/imgui/stb/extensions.kt#L15) do you browse to the code definition?

**Comment by Catvert** [comment]
Yes, i've got the definition of the method in STBRPRect.java
`
/** Returns the value of the {@code was_packed} field. */
    @NativeType("int")
    public boolean was_packed() { return nwas_packed(address()) != 0; }
`
I've noticed that I have this issue since this commit :  https://github.com/kotlin-graphics/imgui/commit/acb3dc3d1e5cb6d4871258c697c9eeec6796ce19
It's very strange xD Thanks fo youe help !

**Comment by elect86** [comment]
Have you tried a clean&build?

**Comment by Catvert** [comment]
Oh yes a lot of times :( 
What's your recommend version of lwjgl, 3.1.6?

**Comment by Sunny1337** [comment]
I had the same problem. The testclasses in Intellijworked fine. But in our project i got the same error and an unsatified link error with the lwjgl-stb.dll. I solved it by building without lwjgl and including the lwjgl 3.1.5 separately into the project.

**Comment by elect86** [comment]
Ok, so, apparently it was a mismatch lwjgl version in dependencies...

imgui still had 3.1.5, which had `was_packed(): Int`

while all the other imgui dependencies had 3.1.6 which had `was_packed(): Boolean`

I just updated now the whole stack to 3.1.7

Give it a try and let me know

**Comment by Catvert** [comment]
Now jitpack.io fail to build the latest commit :(

**Comment by elect86** [comment]
Ops, should be fixed now

**Comment by Catvert** [comment]
It's working thanks for your help !
