### ISSUE TITLE
Extra fonts & issue with lwjgl-stb natives

### ISSUE THREAD

**Issue by kevinmurphy678** [kotlin-graphics/imgui#35]
There seems to be two copies of the fonts in the -SNAPSHOT version. See here: https://i.imgur.com/34H4lWg.png 

And ArialUni takes up 22MB! I was wondering why my jar file was so big. This is easily removed but I think you could get rid of it

On another note:

I also ran into a problem getting it to work on windows with LWJGL-3.1.7-SNAPSHOT(using libgdx 1.9.8). It could not find the native windows files for lwjgl-stb. It only exists up to 3.1.6 on the maven repository.. but strangely there is a linux natives for 3.1.7. I had to use the 3.1.6 stb version which gives a warning on startup but it seems to be working now.

**Comment by elect86** [comment]
Hi,

yeah sorry, that's a missing cleaning I forgot since one of the synchronization delta with the original project (location directory changed)

I didnt investigate that much, but that was the first Arial I manage to quickly find that was supporting japanese..

I'll remove the redundancies in any case. 

However, is it critical/important for you to have a tiny imgui? Is it ok to have all the current fonts available or would you like to have just one?

I'll ask Spasi about LWJGL

**Comment by elect86** [comment]
He said it looks everything fine on [oss](https://oss.sonatype.org/content/repositories/snapshots/org/lwjgl/lwjgl-stb/3.1.7-SNAPSHOT/)

He'll need more information or a small case scenario

**Comment by kevinmurphy678** [comment]
I uploaded the project if you want to take a look at the gradle settings. I'm using intellij idea

https://github.com/kevinmurphy678/BezierProject2/blob/master/build.gradle
https://github.com/kevinmurphy678/BezierProject2/blob/master/core/build.gradle

In the core build.gradle you can see I had to manually add the 3.1.6 stb in order for it to run. On windows It was complaining about a missing stb dll before. But now I just re-tested and removed that line and it still runs fine, so I'm not sure anymore. The error of mismatched natives is still showing up:

[LWJGL] [ERROR] Incompatible Java and native library versions detected.

It works for what I need so it's not really a big deal.

For the fonts it's not really important and I can always remove the ones I don't need. I just wanted to tell you about the redundant copies

**Comment by elect86** [comment]
> For the fonts it's not really important and I can always remove the ones I don't need. I just wanted to tell you about the redundant copies

Thanks, appreciated.

Just committed, that should be fixed now

**Comment by elect86** [comment]
ps: Spasi noted that you seems to be pulling lwjgl3 via the libgdx dependency. Afaict, libgdx is still on LWJGL 3.1.5. He doesn't see anything related to 3.1.7-SNAPSHOT in your project files.

**Comment by elect86** [comment]
He said it looks everything fine on [oss](https://oss.sonatype.org/content/repositories/snapshots/org/lwjgl/lwjgl-stb/3.1.7-SNAPSHOT/)

He'll need more information or a small case scenario
