### ISSUE TITLE
Problem with IDs and imageButtons

### ISSUE THREAD

**Issue by Catvert** [kotlin-graphics/imgui#39]
Hi !

I've found an issue when I use a lot of imageButtons. The program don't crash but imageButtons (the latter, I assume greater than 256 or 512) become unresponsive to the click (and only imageButtons, other elements are responsive as well). The problem is propagated to all windows on the screen having imageButtons.

Thanks for your help,
Catvert.

**Comment by elect86** [comment]
Hi dear,

I just wanted to let you know that I didnt forget you :D

I'm working on a deep restructuration of glm (everything backed by primitive arrays), which will bring as performance improvements more than 10X

It's almost done

**Comment by Catvert** [comment]
Unfortunately, it doesn't seem to be working.
I have another bug since the last commits, popupModals doesn't work anymore, when I open one, the interface freeze and no controls reacts.
Thanks for your help,
Catvert.

**Comment by Catvert** [comment]
Note that normal popup works without problems.

**Comment by elect86** [comment]
Ok, popupModals bug is fixed, thanks

**Comment by Catvert** [comment]
For the other issue, the problem happen when I press an image button in a container that have more than 256 images. The image buttons #255 is working but not the #256.

Thanks,
Catvert.

**Comment by elect86** [comment]
Thanks for the info, I'll have a look

**Comment by elect86** [comment]
Can I debug it if I clone your project?

**Comment by Catvert** [comment]
Hum I will create a simple project, this will be easier.
I post the link here when it's done.
Thanks,
Catvert.

**Comment by Catvert** [comment]
This is the project : https://github.com/Catvert/Imgui-test
Import as a Gradle Project in Intellij Idea and u will be ok.
The main method is in lwjgl3/src/main/kotlin/Lwjgl3Launcher and the game class is in core/src/main/kotlin/Game
I included an exemple with the problem, just scroll down the window and click on the last imageButtons and no console log will be print.
Thanks,
Catvert.

**Comment by elect86** [comment]
Hei Catvert, 

does it work to you? 

Because whenever I try to sync I always get

```
Warning:<i><b>project ':core': Unable to build Kotlin project configuration</b>
Details: java.lang.reflect.InvocationTargetException: null
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':core:compileClasspath'.
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find lwjgl-glfw-natives-windows.jar (org.lwjgl:lwjgl-glfw:3.1.7-SNAPSHOT).
Searched in the following locations:
    file:/C:/Users/gBarbieri/.m2/repository/org/lwjgl/lwjgl-glfw/3.1.7-SNAPSHOT/lwjgl-glfw-3.1.7-SNAPSHOT-natives-windows.jar</i>
Warning:<i><b>project ':lwjgl3': Unable to build Kotlin project configuration</b>
Details: java.lang.reflect.InvocationTargetException: null
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':lwjgl3:compileClasspath'.
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find lwjgl-glfw-natives-windows.jar (org.lwjgl:lwjgl-glfw:3.1.7-SNAPSHOT).
Searched in the following locations:
    file:/C:/Users/gBarbieri/.m2/repository/org/lwjgl/lwjgl-glfw/3.1.7-SNAPSHOT/lwjgl-glfw-3.1.7-SNAPSHOT-natives-windows.jar</i>
```

Also, are you using jave 8, 9 or 10? Because I had troubles with 9 and had to fallback to 8

**Comment by elect86** [comment]
It seems the sync problem was something wrong with my connection.

Anyway, I get now a missing lib `Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll`

**Comment by Catvert** [comment]
Hi ! It's strange, I dont have this issue, I have only tested on Linux, are you running it on Windows ? Perhaps there is a missing lib for Windows ? I'll check in the evening.

**Comment by Catvert** [comment]
Hi ! 
There was indeed a missing lib, I've updated the project.
Thanks,
Catvert.

**Comment by elect86** [comment]
Hi Catvert,

could you update your project to the last imgui snapshot?

**Comment by Catvert** [comment]
Hello, the problem still here.
Best regards, Catvert.

**Comment by elect86** [comment]
I get 

```
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll
	at org.lwjgl.system.Library.loadSystem(Library.java:147)
	at org.lwjgl.system.Library.loadSystem(Library.java:67)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:61)
	at org.lwjgl.system.MemoryStack.<init>(MemoryStack.java:61)
	at org.lwjgl.system.MemoryStack.create(MemoryStack.java:82)
	at org.lwjgl.system.MemoryStack.create(MemoryStack.java:71)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:284)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at org.lwjgl.system.MemoryStack.stackGet(MemoryStack.java:628)
	at org.lwjgl.system.MemoryStack.stackPush(MemoryStack.java:637)
	at org.lwjgl.system.Callback.<clinit>(Callback.java:40)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:78)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:88)
	at Lwjgl3Launcher.main(Lwjgl3Launcher.kt:19)
``` 

I guess because I'm using lwjgl 3.1.7 and your project 3.1.6..

I tried to upgrade to `3.1.7` in the `core\src\build.gradle`, but it keeps saying

> Unable to resolve lwjgl-stb-3.1.7:7

Do you have any idea why?

**Comment by Catvert** [comment]
Hi,
Yes, it doesn't work with 3.1.7 version.
By the way, I think you can easily reproduce the problem on your system. Just tried without libgdx, with your traditional environment and try the following code : 
```kotlin
functionalProgramming.withWindow("Test") {
            for(i in 0..500) {
                if (ImGui.imageButton(-1, Vec2(50f))) {
                    println("Click ! index : $i")
                }
            }
        }
```
normally, you should notice that imageButtons with an index greater than 256 doesn't react to the click (do not display a message in the console).

**Comment by elect86** [comment]
That gives me an opengl error for the invalid textureId I guess.

This works fine, though:
```

        for(i in 0..300)
            if (button("$i"))                             
                println("Click ! index : $i")
```

**Comment by Catvert** [comment]
Hi,
Yes I've just tried, it's working with the button but not the imageButton. Can you try with a blank texture or anything else (the same texture for all buttons is ok) ?
Best regards,
Catvert.

**Comment by elect86** [comment]
so, I guess I narrowed down the problem.

It had to do with the id generation. And since we were relying on bytes, they can only express 256 different values, so even if [our array](https://github.com/kotlin-graphics/imgui/blob/master/src/main/kotlin/imgui/imgui.kt#L82) was 512 slots, it could indeed hold only 256 max different values

Looking for a feedback :)

**Comment by Catvert** [comment]
It's working ! 
Thank you !
Best regards,
Catvert.
