### ISSUE TITLE
Is it possible to use BooleanArray in checkbox ?

### ISSUE THREAD

**Issue by Datoh** [kotlin-graphics/imgui#40]
I would like to generate a checkbox with enum class:

```
enum class Enum1 { E1, E2, E3 }
val enum1ArrayEnabled = BooleanArray(Enum1.values().size)

with (imGui) {
  Enum1.values().forEachIndexed { index, value ->
    checkbox(value.name, ::enum1ArrayEnabled[index])
  }
}
```

`::enum1ArrayEnabled[index]` does not compile, maybe there is another way to do so...

Regards.

**Comment by elect86** [comment]
Unfortunately that is not possible.

But we can simply pass the array itself with an index.

`    checkbox(value.name, enum1ArrayEnabled, index) `

I just pushed, give it a look

**Comment by Datoh** [comment]
I used imgui-kotlin 1.53 and lwjgl 3.1.5
I moved to imgui-kotlin master and lwjgl 3.1.7

But now, I have the current error at run : Caused by: java.lang.Error: No current context. Did you call ImGui::Context() or ImGui::setCurrentContext()?

I add  acontext creation but imGui is not diaplyed anymore:

`class Application : KtxGame<Screen>() {
    private val context = Context()
    private var contextImGui: imgui.Context? = null

    override fun create() {
        val window = GlfwWindow((Gdx.graphics as Lwjgl3Graphics).window.windowHandle)
        contextImGui = imgui.Context()

        LwjglGL3.init(window, false)

        context.register {
            bindSingleton<Viewport>(ScreenViewport())
            bindSingleton<Batch>(SpriteBatch())
            bindSingleton(Stage(inject(), inject()))
            bindSingleton(this@Application)
            bindSingleton(Game(inject(), inject()))
        }

        addScreen(context.inject<Game>())
        setScreen<Game>()
    }

    override fun dispose() {
        contextImGui?.destroy()
        LwjglGL3.shutdown()
        super.dispose()
    }
}`

In more had a compilation error that I remove for now (imgui.IO.wantCaptureMouse is not anymore recognized)

**Comment by elect86** [comment]
That Error is thrown whenever [`gImGui`](https://github.com/kotlin-graphics/imgui/blob/master/src/main/kotlin/imgui/imgui.kt#L23) is still `null` when you want to use imgui to render some gui

Theoretically, after you instantiate the `imgui.Context()`, `gImGui` shouldn't be null anymore. Check that

[`wantCaptureMouse`](https://github.com/kotlin-graphics/imgui/blob/master/src/main/kotlin/imgui/Context.kt#L520) is there, I have no idea why you can't see it

**Comment by Datoh** [comment]
gImGui is initilialized.

Do you know why the imGui window is not displayed?

**Comment by elect86** [comment]
It's very hard to know why without having access to some code.

What I can suggest you, is to start from the tests and then build it up from there

**Comment by Catvert** [comment]
I use KTX in my project, you can check out if you want : https://github.com/Catvert/Platform-Creator
Have a look at this project too : https://github.com/Catvert/Imgui-test, its a simple example with LibGDX but without kTX but you can adapt the code easily.

**Comment by Datoh** [comment]
I found the problem, nothing is drawn unless I call:

`if (ImGui.drawData != null)
  LwjglGL3.renderDrawData(ImGui.drawData!!)`

However, I have JavaVM crash after 10s, it occurs even if I call only `LwjglGL3.newFrame()`

crash log (hs_err_pid4212.log): https://pastebin.com/cV5hKTbR

**Comment by Datoh** [comment]
@Catvert  I have the same crash on your project [](https://github.com/Catvert/Platform-Creator)

**Comment by elect86** [comment]
Try add `appBuffer.reset` in your loop

**Comment by Datoh** [comment]
It works !

But it is a good practice to reset the buffer each frame?

**Comment by elect86** [comment]
Yes, a short explanation is here [here](https://github.com/java-opengl-labs/Vulkan) (but I'll add it in the wiki)

This is the [`appBuffer`](https://github.com/kotlin-graphics/vkk/blob/master/src/main/kotlin/vkk/appBuffer.kt#L16-L19) object.

It's thread-safe and fast because it's just a call to `intAtomic`

Basically it's suitable for any short-live native allocations, included OpenGL and Vulkan native resources, as well as GLFW. Plus anything else the user may ever ned

It gets automatically called if you use the [`window.loop { }`](https://github.com/kotlin-graphics/uno-sdk/blob/master/src/main/kotlin/uno/glfw/GlfwWindow.kt#L309), otherwise you have to do it manually

Ps: you should also call it in the reshape, because if the user start resizing the window dragging for a time long enough he will fill it up

**Comment by Datoh** [comment]
Thanks a lot for the support !

**Comment by elect86** [comment]
I'll close it, if it's fine for you
