### ISSUE TITLE
Crash on sliders sliding into the negative

### ISSUE THREAD

**Issue by chrjen** [kotlin-graphics/imgui#51]
Found in commit 297e44d081e23c16c9ac3dc61bde353f55377ade
Related to #47 #48

Every time a slider has a negative value the following exception happens.

```
(Widgets > Basics)
Exception in thread "hmd-renderer" java.text.ParseException: Unparseable number: "-2%"
	at java.base/java.text.NumberFormat.parse(NumberFormat.java:393)
	at imgui.imgui.imgui_internal$Companion.roundScalarWithFormat(internal.kt:3498)
	at imgui.imgui.imgui_main$Companion.dragBehaviorT(main.kt:658)
	at imgui.imgui.imgui_internal$DefaultImpls.dragBehavior(internal.kt:1552)
	at imgui.ImGui.dragBehavior(imgui.kt:45)
	at imgui.imgui.imgui_widgetsDrag$DefaultImpls.dragScalar(widgets drags.kt:266)
	at imgui.ImGui.dragScalar(imgui.kt:45)
	at imgui.imgui.imgui_widgetsDrag$DefaultImpls.dragScalar$default(widgets drags.kt:212)
	at imgui.imgui.imgui_widgetsDrag$DefaultImpls.dragInt(widgets drags.kt:133)
	at imgui.ImGui.dragInt(imgui.kt:45)
	at imgui.imgui.demo.widgets.invoke(widgets.kt:378)
	at imgui.imgui.demo.ExampleApp.invoke(ExampleApp.kt:180)
	at imgui.imgui.imgui_demoDebugInformations$DefaultImpls.showDemoWindow(demo debug informations.kt:91)
	at imgui.ImGui.showDemoWindow(imgui.kt:45)
	at imgui.imgui.imgui_demoDebugInformations$DefaultImpls.showDemoWindow(demo debug informations.kt:87)
	at imgui.ImGui.showDemoWindow(imgui.kt:45)
	at com.chrjen.pluto.gui.VRScene$VRRenderer.loop(VRScene.java:748)
	at com.chrjen.pluto.gui.VRScene$VRRenderer.lambda$run$0(VRScene.java:270)
	at uno.glfw.GlfwWindow.loop(GlfwWindow.kt:503)
	at com.chrjen.pluto.gui.VRScene$VRRenderer.run(VRScene.java:269)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

This happens for every slider I tried that allows me to slide the value into the negative.

```
DEMO EXCEPTION: Unparseable number: "-0.0004"
DEMO EXCEPTION: Unparseable number: "-59 deg"
DEMO EXCEPTION: Unparseable number: "-0.008700 ns"
DEMO EXCEPTION: Unparseable number: "-425 units"
DEMO EXCEPTION: Unparseable number: "-60"
```

**Comment by chrjen** [comment]
Yeah I just tried running my program on a JVM using a different default local and it doesn't crash anymore. So it only crashes depending on what region of the world you are from, lol.

If you can't reproduce the bug, try running the JVM with the arguments `-Duser.country=NO -Duser.language=no`. I'm also using Java 9 which might be relevant.

**Comment by elect86** [comment]
`-Duser.country=NO -Duser.language=no` did actually help to reproduce the error, coz I was having no excepetion with negative `ns` float dragging field.

Uhm, that's tricky to resolve. Shall we maybe detect and react according to the current locale?

Any tips?

Which was your original locale that provoked the crash?

**Comment by chrjen** [comment]
My original locale is Norwegian no_NO. 

I can really give any tips though as I have no idea what `roundScalarWithFormat` does or why the parse is necessary. Rounding by converting to string, then back again seems really strange to me (at least that's what I think it is doing).

**Comment by elect86** [comment]
In a comment, Omar wrote `Round to user desired precision based on format string`

I'll think about it

In the meanwhile... why the hell does it crash with negative values using Norwegian locale...? lol

Anyway, I just pushed a workaround, `DecimalFormat` will always use as locale `style.locale` (which is now a `var`)

**Comment by elect86** [comment]
I have no idea neither, but I'd guess he has his reasons, I need to check if this makes sense on jvm as well

Anyway, lol, man, what's wrong with norwegian format.. :grin:

Pull again, dear. This time I also trim the begin of the string

As I said, default it `us`, but you can change it. It's `style::locale`

**Comment by chrjen** [comment]
Ah, thank you. Though of course currently changing local breaks the library..

I don't know why Norwegian is suppose to use a different minus sign. Also I just noticed I didn't seem to actually post the link in my previous comment like I intended you to read -_-. Anyway this is what I found, [link](https://bugs.openjdk.java.net/browse/JDK-8189097). In the reply it also links to a page on unicode that list which locals have different minus signs. So Norwegian is there (nb/nn) though not the only one using that special minus sign, but also Finnish, Swedish, Italian, etc.

**Comment by chrjen** [comment]
> What do you mean?

Sorry, locale*.

Change the locale in imgui.style to e.g. Norwegian causes the same issues again. I mean your fix was to set the locale to US so naturally setting it to e.g. Norwegian again will make the unparseable number exception happen again.

**Comment by elect86** [comment]
I dont get any more exceptions..

I'm parsing now strings with `DecimalFormat`, it looks working flawless also for Norwegian locale

Give it a try

**Comment by chrjen** [comment]
Tried commit fd684222e4c6cab94f2e8535a2693c362089c417 and it still throws the same ParseException as usual.

Just looking at the commit though I see nothing that has really changed except the default locale for everyone is now Norwegian instead of US.

**Comment by elect86** [comment]
Shit, that was unwanted :p

Anyway, I dont get why I dont get anymore the exception.. 

I tried passing `-Duser.country=NO -Duser.language=no` to JVM args..

Anyway, I can still reproduce with

    val dec = DecimalFormat().apply {
        decimalFormatSymbols = DecimalFormatSymbols(Locale("no", "NO"))
    }
    dec.parse("-5")

So, let's face the problem from another point of view, let's substitute the old minus with the new out

Give me good news, man ^^

**Comment by elect86** [comment]
Ok, then let's switch it only given on the `style.locale`

Anyway, I'm going crazy.

You can easily do it and test on your machine, since you can reproduce it easily.

Do you mind working on it directly? :)

**Comment by Sylvyrfysh** [comment]
If needed, chrjen could join lwjgl slack and message you there

**Comment by chrjen** [comment]
Well I can always try to help. Don't know why the username doesn't work. Also don't really know Kotlin, but a solution in Java shouldn't be very hard to translate into Kontlin, right?

**Comment by elect86** [comment]
> If needed, chrjen could join lwjgl slack and message you there

Also, as he prefers

> Well I can always try to help. Don't know why the username doesn't work. 

Try to send me your email, here or on elect86 gmail

> Also don't really know Kotlin, but a solution in Java shouldn't be very hard to translate into Kontlin, right?

Right and then you'll love it and you are gonna switch everything to Kotlin :)
