### ISSUE TITLE
Going to remove jogamp backend

### ISSUE THREAD

**Issue by elect86** [kotlin-graphics/imgui#56]
As titled, I'm planning to remove the jogamp (GL3 and VR) backend in the short future because I won't need it anymore

This will allow to focus my efforts on lwjgl backends and reduce the dependency list and in turn also the build size..

If anyone is still relying/using that, please step in

**Comment by Sylvyrfysh** [comment]
I'm down for dropping it regardless, as while we do not use the most recent APIs, they are not supported. This means that if you do run into an issue with them, we have no way of effectively remedying the issue.

**Comment by Sylvyrfysh** [comment]
Probably should finalize this, if it hasn't been already

**Comment by elect86** [comment]
I'm gonna do this soon, we still rely on it atm

**Comment by elect86** [comment]
It appears to be some latest movement on jogamp ([here](http://forum.jogamp.org/JogAmp-2-4-0-rc-Autobuild-td4039672.html))

I'd sospend the removal for the moment

Let's see how things go on

**Comment by Sylvyrfysh** [comment]
I think we can call this a non-issue. Now that we're modular, it's not like you need to pick a backend, so leaving one in doens't matter so much.

**Comment by elect86** [comment]
Correct
