### ISSUE TITLE
MemoryStack leak in v1.6.3-beta-02

### ISSUE THREAD

**Issue by DomWilliams0** [kotlin-graphics/imgui#57]
The thread local `MemoryStack` is leaking frames and leads to an `OutOfMemoryError`. This isn't present in v1.6.3-beta-01.

Reproduce when running the [LWJGL example](https://github.com/kotlin-graphics/imgui/blob/master/src/test/java/imgui/gl/Test_lwjgl.java) by printing `MemoryStack.stackGet().pointer` in the main loop - on beta-01 this remains constant (as it should) but on beta-02 falls to 0 and crashes.

**Comment by elect86** [comment]
Thanks, I'll look into it

**Comment by elect86** [comment]
One deadly `return` in uno for retrieving window size before `stack.pop` could be executed.. tricky

thanks for let me know  

I'll update the jars

**Comment by DomWilliams0** [comment]
Thanks for fixing it. However, downloading it through jitpack still fetches the old version of uno-sdk. Maybe its worth bumping the version number?

**Comment by elect86** [comment]
I explicitely cleaned the build on jitpack, the first pull shall trigger a new build now

Otherwise I'll bump

**Comment by DomWilliams0** [comment]
Just tried from another machine, still pulls the old one.

**Comment by elect86** [comment]
ok, new release out :p
