### ISSUE TITLE
dragVec3 receiving Vec2 as parameter

### ISSUE THREAD

**Issue by vfmachado** [kotlin-graphics/imgui#59]
Hello,

I'm starting use imgui to test my graphic framework with LWJGL, OpenGL, GLFW...

When I got something working I realized the function dragVec3 seemes to be wrong.

It receiving a Vec2 instead a Vec3.

The Vec3i is correct, I'm using it for now... but I would like ask you to check it.

Thank you.

**Comment by elect86** [comment]
Oh, you are right

I'll fix it this evening, I'm not at the right machine now

Otherwise if you want to push it, feel free :)
