### ISSUE TITLE
Instances of Vec2 created during execution

### ISSUE THREAD

**Issue by vfmachado** [kotlin-graphics/imgui#60]
Hello, I'm justing started using ImGUI with your port and I realized that there are a lot of instances being created in my application.

I put just the demo window in my application and this is the result.

There is a solution for this behavior? Thank you

**Comment by elect86** [comment]
Hi,

yeah, `Vec2` is the most common class in the project (you can see it also [here](https://github.com/ocornut/imgui/search?q=vec2&unscoped_q=vec2))

> There is a solution for this behavior? Thank you

The solution would be to switch all the classes to float fields, and change consequently all the function signatures, class properties and the code using those classes, also giving up on operator overloading and making code much more verbose, less similar to the original C++ and more error prone.

I never experienced problems with that, even on old laptops from 7/8 years. 

But if it's a problem on your machine, if you want you may want to give a try and change all of that and see if you get any benefit in term of performances.

You could take care of a branch for that

**Comment by elect86** [comment]
Hi, 

I'm sure I replied but I dont see my reply here, did you get it?

**Comment by elect86** [comment]
Hi,

yeah, Vec2 is the most common class in the project (you can see it also here)

    There is a solution for this behavior? Thank you

The solution would be to switch all the classes to float fields, and change consequently all the function signatures, class properties and the code using those classes, also giving up on operator overloading and making code much more verbose, less similar to the original C++ and more error prone.

I never experienced problems with that, even on old laptops from 7/8 years.

But if it's a problem on your machine, if you want you may want to give a try and change all of that and see if you get any benefit in term of performances.

You could take care of a branch for that

**Comment by vfmachado** [comment]
Thanks for your answer.

I'm still evaluating the Project with ImGUI and two years ago I got a similar problem with buffers so I'm being cautious about memory usage =D

Hopefully, This will not be a problem.

**Comment by elect86** [comment]
I'm using chrome and everything is displayed fine now

Apparently the problem comes from Firefox.. 

Ps: what are you using?

Anyway, which kind of buffers? Because that may be a much more sensitive thematic

Also, take in account that most of the classesinstances will be taken out by compiler optimizations, such as escape analysis

Moreover:

> Programmers waste enormous amounts of time thinking about, or worrying about, the speed of noncritical parts of their programs, and these attempts at efficiency actually have a strong negative impact when debugging and maintenance are considered. We should forget about small efficiencies, say about 97% of the time: premature optimization is the root of all evil. Yet we should not pass up our opportunities in that critical 3%.  ([cit.](https://en.wikiquote.org/wiki/Donald_Knuth))
