### ISSUE TITLE
Multiple OS windows / contexts with imgui

### ISSUE THREAD

**Issue by exuvo** [kotlin-graphics/imgui#67]
So i finally got this working.
Had to make ImplGL3 and LwjglGlfw instantiable and move some things from impl/common.kt to ImplGL3 for it to work but pretty small changes overall.

Before i make a pull request i assume it would be best to keep the current API working? Which i think i can do by making a companion object with the same method names that keeps 1 instance statically.
I'll can also whip up a short test file to demonstrate usage.

If you want me to add some instructions I'll probably need wiki edit rights too.

The picture shows the same program having 3 separate views open of the same game instance.
![multiple windows](https://user-images.githubusercontent.com/2049338/52385232-f7052200-2a80-11e9-8919-ba9820c00a1b.png)

**Comment by Sylvyrfysh** [comment]
In the past we have done breaking API changes for major new features /
internal changes. If you can keep it backwards compatible I think that's
great, but this is a big enough feature that breaking backwards
compatibility isn't a blocker to me.

On a side note, if you can update the tests to make them work, that'd be
great

**Comment by elect86** [comment]
Hello @exuvo,

I totally agree with @Sylvyrfysh, if it makes sense, then a breaking change is always welcome. Beside that, even the original author, Omar, makes quite a lot of them himself.. He is actually working on something [similar](https://github.com/ocornut/imgui/issues/2109), but we can totally use your solution in the meanwhile

Anyway, nice job. 

We can see how it looks like in a separate branch for the moment (I find it easier to work on it), I'll add you

**Comment by exuvo** [comment]
Just wasted a few hours trying to get my eclipse to run kotlin mains, but it is being stupid and not compiling kotlin files to .class files for running them.
Just gave up on that for now and ran them from a gradle task instead.

Existing java and kotlin test files still run after my modifications.
API is unchanged for kotlin but for java there is minor changes needed.

Pushed to branch exuvo 0d43c6ce2cae23787ef7b801644606ed7fc1fe5e
The new test file has tabs for indentation i hope that is okay. Ugh github uses 8 spaces for a tab..

**Comment by Sylvyrfysh** [comment]
Can you make a pull request? I'll review it then

**Comment by elect86** [comment]
@exuvo, I'd not waste time running kotlin on other IDEs, if it's ok for you simply use Idea for that, it'll avoid you a lot of pain

I dont care about indentation, although it's highly probable I'm gonna modified it sooner or later because I'm used to auto-format periodically

For me it looks fine.

Also, another idea may be to have a default `LwjglGlfw` always instantiated and then any other additional one shall be created at will.

Ps: we could just move the new companions at the bottom of the class for the sake of following kotlin conventions, but this is really picky.

**Comment by exuvo** [comment]
@elect86 I mostly use eclipse because it works for both java, kotlin and embedded c/c++. Just tried intelliJ and it seems impossible to support the mixed "source" and "resources" structure i use, so i am going to keep using eclipse even if the kotlin support is marginal.
