### ISSUE TITLE
Collapsing window issue

### ISSUE THREAD

**Issue by Catvert** [kotlin-graphics/imgui#7]
Hello, I have an issue when I collapse a window when i'm using functionalProgramming.window, the window disappeared and is replaced by a debug window. 
I have no problem when i'm using begin() with end().

Example : 
```kotlin
functionalProgramming.window("Test", null) {
  button("test button")
}
```

**Comment by elect86** [comment]
Hi, 

However, cpp code crashes when I collapse that

I dont know which are the conditions under which you should use that construct, but I can tell that you should use `withWindow`


        if (!begin(name)) {
            ...
        }
        end()

`window` is the shortcut for 

        if (!begin(name)) {
            ...
            end()
        }

In general, all the plain name involve always an `if`, all those that start instead with `with*` have a begin/end construct

Let me know if it works

**Comment by Catvert** [comment]
Yes it works, thanks for the information and sorry for the inconvenience.

**Comment by elect86** [comment]
You are welcome, no inconvenience at all

I'll expand the wiki with that sooner or later :)
