### ISSUE TITLE
Functions visibility outside library

### ISSUE THREAD

**Issue by yuraj11** [kotlin-graphics/imgui#73]
Is there any reason for library extension methods (and other stuff) to be public outside library? I know It does nothing but It may "pollute" code completion.
![image](https://user-images.githubusercontent.com/5477518/52657303-a403f280-2ef8-11e9-9429-2c50e35563ec.png)

**Comment by elect86** [comment]
This shouldn't happen.. uno-sdk is using {`implementation`](https://github.com/kotlin-graphics/imgui/blob/master/build.gradle#L26) keyword which should not make leak internal dependencies..

How are you importing imgui?

**Comment by yuraj11** [comment]
I compile JAR from latest branch changes using provided light jar task and in my project I use this:
```
compile 'com.github.kotlin-graphics:uno-sdk:9172395e2d33107df96fcbc889b6332b0bc4925c'
compile files("../libs/imgui-light.jar")
```

**Comment by elect86** [comment]
which version of gradle are you using?

**Comment by yuraj11** [comment]
`gradle-4.10.3` and now I have tried `gradle-5.1` and It also happens there.

**Comment by elect86** [comment]
try `implementation` instead `compile` and sync again

**Comment by yuraj11** [comment]
```
        implementation 'com.github.kotlin-graphics:uno-sdk:9172395e2d33107df96fcbc889b6332b0bc4925c'
        implementation files("../libs/imgui-light.jar")
```
and gradle-5.1
but still the same problem (I have also invalidated intellij cache)

**Comment by yuraj11** [comment]
Maybe you should add `internal` modifier to module specific properties and functions?

**Comment by elect86** [comment]
that'd be overkill, there are thousands of places where that would need to be added

Moreover I do use also heavily glm and gli when I usually import uno..

Could you consider ask it on stackoverflow?

**Comment by yuraj11** [comment]
Ok I will try to do something on my side. Feel free to close this issue.

**Comment by elect86** [comment]
We can leave it open till you have some news about the issue

**Comment by yuraj11** [comment]
Currently the only solution for this is to make separate module in my project where I will use the library there or make an interface (but that is overkill).

**Comment by elect86** [comment]
This should be addressed since we use `implementation` for all our dependencies since a while now
