### ISSUE TITLE
Max items ?

### ISSUE THREAD

**Issue by Catvert** [kotlin-graphics/imgui#8]
Hello, I'm trying to add a method to display a list of selectable texture in a window with imageButtons. But when there are more than 125 buttons in the window, buttons (with an index > 125) don't react to the click. I tried to use a withId (index) to make sure they have a different id but it doesn't change anything. Thanks to you, Catvert.
![sans titre](https://user-images.githubusercontent.com/8643204/33240211-bed8db3c-d2b2-11e7-85f0-a1c304e09891.png)

**Comment by elect86** [comment]
Salut!

I set a deep of integers to 100, maybe it's that (125 looks weird..)

Anyway, I increases to 500

pull again and let me know :)

Ps: cool screenshot! Once you reach a nice point, would you like to share it in a gallery?

**Comment by Catvert** [comment]
I thought the problem had to be internal! 
Of course, as soon as I have a satisfying result, I will share screenshots! 
Thanks again !

**Comment by Catvert** [comment]
Hi, I didn't check if the patch worked but apparently it doesn't work, I still have the same problem.

**Comment by elect86** [comment]
Uhm, I should debug that, is it always the same project? How can I reach that menu?

**Comment by Catvert** [comment]
Yes, It's in Platform-Creator, the code is situate in the last commit to the components/graphics/AtlasComponent.kt line 307, and in the game, open the game, click on the button Jouer then on the button Nouveau then click on Créer. Now in the editor, left click on the player, it should open a properties gameobject window, then open the collapsing header components, select the AtlasComponent then click on the Éditer button. It should open a window and in it just expand the collapsing header Ressources. You will now have the image buttons to change the texture of the gameobject, when there is a large number of image button, for example in the pack "elements", buttons with an index greater than ~ 100 no longer respond to the click. I hope I have been clear enough, if you have questions I am here. Thanks

**Comment by elect86** [comment]
Thanks for description, it was useful.

Anyway, problem had to do with the fact that 

`System.identityHashCode(++ptrIndices)`

where 

`var ptrIndices = 0`

didn't return always the same value for integers bigger than 125

I have no idea why, but I tested using bytes instead and it works (please don't ask why ^^, I'll open an issue on stackOverflow maybe)

Anyway, I don't have the possibility to test it now, so if you can I'm looking forward to know if it does work for you

**Comment by Catvert** [comment]
I tested and the solution seemed to work but I then encounter another problem when there are more than 256 buttons, I get:
 ```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 256
	at imgui.internal.Window.getId(classes.kt:505)
	at imgui.imgui.imgui_idScopes$DefaultImpls.pushId(idScopes.kt:19)
	at imgui.ImGui.pushId(imgui.kt:29)
	at imgui.imgui.imgui_widgetsMain$DefaultImpls.imageButton(widgetsMain.kt:115)
	at imgui.ImGui.imageButton(imgui.kt:29)
	at imgui.imgui.imgui_widgetsMain$DefaultImpls.imageButton$default(widgetsMain.kt:108)
```
I don't know if this problem is voluntary or not, but I can't find an effective way to fix it, I've tried to create a group every time there are more than 256 items but I still have this error that happens.

**Comment by elect86** [comment]
Doubled the size to 512, is it enough?

**Comment by Catvert** [comment]
Yes it's perfect !  it works like a charm :)

**Comment by elect86** [comment]
Excellent 👍

**Comment by Catvert** [comment]
I have another question while we're at it ahah, when do you think the inputText will work? What's your problem with it? :)

**Comment by elect86** [comment]
> I have another question while we're at it ahah,

sure dear ^^

> when do you think the inputText will work? What's your problem with it? :)

:D I need to find time to seriously drive deep inside it, however if you point me out simple dead bugs I might be try to focus on that singularly at the moment (step by step)

**Comment by Catvert** [comment]
Of course, I'd be happy to help you! I use a lot of inputText in my game so I can easily find some bugs. Do you want me to open a new issue to discuss in this one? :)

**Comment by elect86** [comment]
As you prefer, although maybe a separate issue may be more useful to distinguish from other ones and be easier to be tracked by users

**Comment by Catvert** [comment]
Yeah, that's what I thought.
