### ISSUE TITLE
Memory Leak ?

### ISSUE THREAD

**Issue by xpenatan** [kotlin-graphics/imgui#82]
![image](https://user-images.githubusercontent.com/6472084/55598683-62d6d480-572a-11e9-916f-9ae7980d3696.png)

Hi, is there a memory leak in master branch and 1.68.01-00 tag ?
Toke me a while to get it to show with libgdx but now I have this issue.

```Java
public class Mymain implements ApplicationListener {


    private GlfwWindow window;
    private LwjglGlfw lwjglGlfw;
    private ImGui imGui;
    private Context context;

    @Override
    public void create() {
        imGui = ImGui.INSTANCE;
        Lwjgl3Graphics graphics = (Lwjgl3Graphics) Gdx.graphics;
        Lwjgl3Window window = graphics.getWindow();
        this.window = GlfwWindow.from(window.getWindowHandle());
        context = new Context(null);

        LwjglGlfw.Companion.init(this.window, true, GlfwClientApi.OpenGL, null);;
        lwjglGlfw = LwjglGlfw.instance;
    }

    @Override
    public void resize(int width, int height) {

    }

    boolean[] a = new boolean[]{true};

    @Override
    public void render() {

        Gdx.gl.glClearColor(0.2f, 0.2f, 0.2f, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);

        lwjglGlfw.newFrame();
        imGui.newFrame();

        imGui.begin("Demo_0", a, 0);
        imGui.text("Hello, world!");
        imGui.end();

        imGui.render();

        DrawData drawData = imGui.getDrawData();
        ImplGL3.Companion.renderDrawData(drawData);
    }

    @Override
    public void pause() {

    }

    @Override
    public void resume() {

    }

    @Override
    public void dispose() {

    }
}
```

I used this current code. Is it wrong ?

both newFrame  method is the cause to max out my 16gb ram

**Comment by elect86** [comment]
That looks fine.

What happens if you comment the imgui lines (all)?

I tried running the test demo for 20m and the difference in terms of allocations is minimal, it's mostly char arrays and strings..

Begin:
![image](https://user-images.githubusercontent.com/5020626/55616371-f8597f00-5791-11e9-9f43-43a2f1ecf85f.png)
After 20m:
![image](https://user-images.githubusercontent.com/5020626/55616402-07d8c800-5792-11e9-9179-f20b11dd1e93.png)

**Comment by elect86** [comment]
Hi, 

I investigated about native memory leaks, there was about 10 KB stuff leaking. I fixed the most relevant ones, (the remaining leaks are around 200 bytes in total)

Reopen it if you have any news
