### ISSUE TITLE
Custom file name not used when loading ini file

### ISSUE THREAD

**Issue by antbern** [kotlin-graphics/imgui#84]
While upgrading to the latest version of this library (v1.60wip-beta-01 -> v1.68.01-00), I found that the ini file was not loading correcly from a custom path anymore. I looked into the source and found that the custom file name was not used at all when loading:
https://github.com/kotlin-graphics/imgui/blob/c7c8c2c7d5503d0303ff8f38f830958bf8fce0e1/src/main/kotlin/imgui/internal/helpers.kt#L214-L217

I suspect it's as easy as changing `Paths.get("imgui.ini")` to `Paths.get(filename)`.

**Comment by Sylvyrfysh** [comment]
You're correct. If you want to fix and create a PR i'll merge it faster, or i'll fix it when I have access to my laptop

**Comment by elect86** [comment]
Oh, I saw this issue later than the PR, which is already merged
