### ISSUE TITLE
Using KMutableProperty0 in java?

### ISSUE THREAD

**Issue by MrManiacc** [kotlin-graphics/imgui#86]
I'm trying to implement a list box, for file dialog. I'm using the java lwjgl 3 bindings and i can't figure out how to give it a `KMutableProperty0 <Int>` in java. I may be overseeing something but i'm at a loss.

**Comment by Sylvyrfysh** [comment]
This is something I believe @elect86 looked in to, but was unable to get
anywhere with. I'll take a look in the next few days, but if you need an
immediate workaround, you can use an int array of size one. ImGui will
modify the first element, and you can access it with array[0].

**Comment by elect86** [comment]
Exactly.

This needs further investigation, rely on the array version for the moment. If it's missing we can add it

**Comment by MrManiacc** [comment]
When trying to use an int array, I get the following error: Wrong 2nd argument type. Found: 'int[]', required:'kotlin.reflect.KMutableProperty0<java.lang.Integer>

**Comment by elect86** [comment]
here you go: 87aa5b881ded888ae39f263b7d68e1a993b125ad

**Comment by MrManiacc** [comment]
Awesome. Working fine now, thank you!
