### ISSUE TITLE
calcTextSize width 0

### ISSUE THREAD

**Issue by yuraj11** [kotlin-graphics/imgui#89]
With latest changes - calcTextSize X returns 0

**Comment by elect86** [comment]
I put a breakpoint at `calcTextSize`, and the first call is `calcTextSize("Debug##Default")` which returns `Vec2(35, 13)` as the c++

Which parameters are you passing?

**Comment by yuraj11** [comment]
`calcTextSize("some text", false)`

**Comment by yuraj11** [comment]
Hm, have you check lwjgl demo? Fonts of some ui widgets are not rendered correctly now.

**Comment by elect86** [comment]
Thanks

**Comment by yuraj11** [comment]
Almost fixed but I still see issues with context/popup menus - they are not rendered correctly.

**Comment by yuraj11** [comment]
+ selectable

**Comment by elect86** [comment]
Try again.

There were some other parameters to set to a "jvm null" (that is -1, I prefer to avoid nullability when possible)
