### ISSUE TITLE
Infinite Iteration Tools / Functions

### ISSUE THREAD

**Issue by Mr00Anderson** [kotlin-graphics/imgui#95]
Infinite Iteration Tools / Functions for primitive values for now, arrays can be another feature anotyher time. In the `imgui_widgets_inputWithKeyboard.kt#inputScalar` values are clamped through ` internal.kt#dataTypeApplyOp`. It would be useful to add either an option or just statically code the values to loop on its last exclusive value. Example: a byte 127 would instead increment to -128 then being clamped on "+".

I do not have a time frame when I could add this just yet.

**Comment by Sylvyrfysh** [comment]
Check what original ImGui library does, I don't believe this is the
behavior (but I could be wrong)

**Comment by Mr00Anderson** [comment]
@Sylvyrfysh Unlikely; also did not think about that this is just a re-write of the original.
