### ISSUE TITLE
Issues with inputs

### ISSUE THREAD

**Issue by yuraj11** [kotlin-graphics/imgui#97]
There are still issues with inputs on latest master. Open demo - widgets - basic - try editing inputs. If you will delete input content and the write something shorter than previously It will overwrite part of old string.

**Comment by Sylvyrfysh** [comment]
Confirmed

**Comment by Sylvyrfysh** [comment]
Somewhere between e9d51cbc9eafab8dbab26d8a8ed7debe50577c9e and a94d11f135c4967a949f6403775a6765890232cb . I'll keep narrowing and attempt fix when i have the time
